### PR TITLE
Add dockerized option of raintank-collector

### PR DESCRIPTION
**Pull request by jangaraj**
I've published dockerized version of raintank-collector. People don't like current install option #25 - this docker image will be much faster (~30sec) option for them.

### CODE REVIEW

**Comment by jangaraj** [comment]
@woodsaj PR #39 has been merged - thank you. Now also Dockerfile uses raintank-collector master branch. Docker images tested and verified. Could you merge also this PR please?

**Comment by woodsaj** [comment]
@jangaraj I would prefer not to link to packages maintained by others. As we have no control over the build process of you docker image.

We do use circleci to to build debian packages and would be eager to extend the circleci integration to also build and publish updated docker images when ever commits are merged into master.

**Comment by jangaraj** [comment]
@woodsaj 

> As we have no control over the build process of your docker image.

I'm happy to provide RW access. Actually it's not a package, but automated build of docker image => build process is fully transparent and public, user can always identify the code (repo), which has been used in the build process. I will have more security concerns, if you are pushing Docker images from the third party sites (e.g. circle ci).

> Would be eager to extend the circleci integration to also build and publish updated docker images when ever commits are merged into master.

Perfect, but you still didn't publish it and I did. You have already mentioned that PR are welcome and now you don't want to merge my PR.This one can be my show stopper of being part of raintank community. Also please test it - it's not a Debian image :-) This is optimized production docker image. Your Debian dockerfiles are optimized for dev process, not for production.

I'm not accepting your opinion, so please find another solution: fire/hire me, mark it as a community project (check my similar project in [grafana-docker readme](https://github.com/grafana/grafana-docker)), accept RW access, ...

**Comment by woodsaj** [comment]
My biggest concern is that we cant trigger a new docker image to be published when we commit changes, so users using the docker images may not be using the latest version.

But having the docker image available is a very big win for the community and your efforts to provide it are greatly appreciated. 

I have created a new PR which extends your branch and adds additional instructions for installing using a Deb Package (which we already build and publish to PackageCloud.io every time we commit to master). You may also want to consider using this package in your Docker image to simplify things.

Check it out and let me know what you think.  https://github.com/raintank/raintank-collector/pull/41

**Comment by jangaraj** [comment]
Replaced by #41

**Pull request closed without merging**
