### PR TITLE
circleci and packaging refactoring

### PR DESCRIPTION
**Pull request by splaspood**
Cleaned up / simplified circleci.yml, moved packaging to scripts in pkg/

Will require PACKAGECLOUD_REPO='raintank/unstable' to work going forward.

### CODE REVIEW

**Comment by woodsaj** [comment]
jwb, this is looking good.  I dont see anywhere in the build process where build.sh is called to build the ./go-ping binary,  (this will be changing ./raintank-probe with https://github.com/raintank/raintank-collector/pull/20)  

@splaspood

**Comment by splaspood** [comment]
You are correct, I'll take a look.

**Comment by ctdk** [comment]
One question: the PACKAGECLOUD_REPO environment variable is a great idea, but it occurred to me that we'll probably want to be able to deploy different branches to different repos. Can we set env vars conditionally in circle.yml, or will we need to be more clever?

**Comment by splaspood** [comment]
What do you mean conditionally?

**Comment by ctdk** [comment]
Meaning like setting PACKAGECLOUD_REPO to different values depending on what branches you're pushing. As far as I can tell the environment variables are per-project rather than per-branch.

**Pull request merged**
